services:
  - type: web
    name: quant-fund-gui
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TIINGO_API_KEY
        sync: false
